=== Amaroke/ArchivesS8/XML/TP1/couleur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


    <xsd:element name="nomDeCouleur">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="piece" minOccurs="1" maxOccurs="16">
                    <!-- Définition d'une pièce -->
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nom" type="xsd:string"/>
                            <xsd:element name="position">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="colonne" type="xsd:string"/>
                                        <xsd:element name="ligne" type="xsd:integer"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Amaroke/ArchivesS8/XML/TP1/couleur.xml
<?xml version="1.0" encoding="UTF-8"?>
<nomDeCouleur xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="couleur.xsd">


    <piece>
        <nom>roi</nom>
        <position>
            <colonne>G</colonne>
            <ligne>1</ligne>
        </position>
    </piece>

    <piece>
        <nom>fou</nom>
        <position>
            <colonne>D</colonne>
            <ligne>6</ligne>
        </position>
    </piece>

    <piece>
        <nom>pion</nom>
        <position>
            <colonne>H</colonne>
            <ligne>5</ligne>
        </position>
    </piece>

    <piece>
        <nom>reine</nom>
        <position>
            <colonne>H</colonne>
            <ligne>4</ligne>
        </position>
    </piece>

</nomDeCouleur>
