<?xml version="1.0" ?>
<!DOCTYPE forum [
        <!ELEMENT forum (personnes|messages)*>
        <!ELEMENT personnes (personne)*>
        <!ELEMENT personne (nom|prenom|adresse)*>
        <!ATTLIST personne
                ref CDATA #REQUIRED>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>
        <!ELEMENT adresse (#PCDATA)>
        <!ELEMENT messages (message)*>
        <!ELEMENT message (expediteur|texte|anterieur)*>
        <!ATTLIST message
                ref CDATA #REQUIRED>
        <!ELEMENT expediteur (#PCDATA)>
        <!ATTLIST expediteur
                ref CDATA #REQUIRED>
        <!ELEMENT texte (#PCDATA)>
        <!ELEMENT anterieur (#PCDATA)>
        <!ATTLIST anterieur
                ref CDATA #REQUIRED>
        ]>
<forum>
    <personnes>
        <personne ref="p1">
            <nom>colotte</nom>

            <prenom>vincent</prenom>

            <adresse>vincent.colotte@loria.fr</adresse>
        </personne>

        <personne ref="p2">
            <nom>lotfi</nom>

            <prenom>bellalem</prenom>

            <adresse>bellalem@loria.fr</adresse>
        </personne>
    </personnes>

    <messages>
        <message ref="m1">
            <expediteur ref="p1"/>

            <texte>Bonjour</texte>
        </message>

        <message ref="m2">
            <expediteur ref="p2"/>

            <texte>Hello</texte>
        </message>

        <message ref="m3">
            <expediteur ref="p2"/>

            <texte>Bonjour, Ca va bien ?</texte>

            <anterieur ref="m1"/>
        </message>

        <message ref="m4">
            <expediteur ref="p1"/>

            <texte>Ca va !!</texte>

            <anterieur ref="m3"/>
        </message>
    </messages>
</forum>

